version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: dependent
        changed:
          files: ['package.json', 'yarn.lock']
          message: When updating `package.json` please also add an update to the `yarn.lock` file.